markdown: rdiscount
pygments: true
permalink: /posts/:title
rdiscount:
  extensions: [smart]

name: Philip Hale
url: http://pghale.com
description: A fantastic blog that is fantastic.
twitter: philip_hale
github: hale
gravatar_url: https://secure.gravatar.com/avatar/ad36144df4cde05a4b1d9bb3602690bc.png
