markdown: rdiscount
permalink: /posts/:title
rdiscount:
  extensions: [smart]

name: Philip Hale
url: http://pghale.com
description: Philip Hale, full time student and web developer.
twitter: philip_hale
github: hale
gravatar_url: https://secure.gravatar.com/avatar/ad36144df4cde05a4b1d9bb3602690bc.png
email: phil989@gmail.com
